### ISSUE TITLE
Cookie section is not working

### ISSUE THREAD

**Issue by 007divyachawla** [UltimateHackers/XSStrike#15]
Hi bro, just download the tool but i want to add cookie section which is not working. please provide the soultion.

**Comment by AnimeshShaw** [comment]
Agreed. I faced the same issue. After looking at the code, modifying line 686 solves the problem.

*Error:*
```
Traceback (most recent call last):
  File "xsstrike", line 699, in <module>
    input() #This is the true start of the program
  File "xsstrike", line 686, in input
    br.addheaders('Cookie', cookie)
TypeError: 'list' object is not callable
```

*Solution*

```python 
br.addheaders.append(('Cookie', cookie))
```
