### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by pr0letariat** [UltimateHackers/XSStrike#18]
I am running the tool against: https://pentesterlab.com/exercises/web_for_pentester

Get the following error:

```
$ python xsstrike
  ____  ___  _________ _________ __          __ __           
  \   \/  / /   _____//   _____//  |________|__|  | __ ____  
   \     /  \_____  \ \_____  \\   __\_  __ \  |  |/ // __ \ 
   /     \  /        \/        \|  |  |  | \/  |    <\  ___/ 
  /___/\  \/_______  /_______  /|__|  |__|  |__|__|_ \\___  >
        \_/        \/        \/                     \/    \/ v2.0

[~] Checking for update
[?] Enter a url: http://192.168.0.31/xss/example1.php?name=hacker
[?] Enter cookie (if any): 
[?] Would you like to look for hidden parameters? [y/N] 
[+] WAF Status: Offline
--------------------------------------------------
[~] Testing parameter name
[+] Filter Strength : Low or None
[+] Payload: <svg/onload=(confirm)()>
[+] Efficiency: 100%
[?] A payload with 100% efficiency was found. Continue scanning? [y/N] 
Traceback (most recent call last):
  File "xsstrike", line 757, in <module>
    input() #This is the true start of the program
  File "xsstrike", line 750, in input
    initiator(url, GET, POST)
  File "xsstrike", line 659, in initiator
    filter_checker(url, param_data, GET, POST) # Launces filter checker
  File "xsstrike", line 246, in filter_checker
    print '%s Target doesn\'t seem to respond properly. Error Code: %s' % (bad, re.search(r'\d\d\d', str(e)).group())
AttributeError: 'NoneType' object has no attribute 'group'

```

**Comment by UltimateHackers** [comment]
Thanks for reporting the issue. It will be patched within 30 mins.

**Comment by UltimateHackers** [comment]
[Fixed] Thanks again ^_^
