### ISSUE TITLE
Not working in mac

### ISSUE THREAD

**Issue by irshad9998** [UltimateHackers/XSStrike#24]
Not working in mac.

When i run `python xsstrike` following error occur.

 `[~] Checking for updates...
Traceback (most recent call last):
  File "xsstrike", line 128, in <module>
    update()
  File "xsstrike", line 39, in update
    xsstrike = br.open('https://github.com/UltimateHackers/XSStrike/blob/master/xsstrike').read()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_mechanize.py", line 254, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_mechanize.py", line 284, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_opener.py", line 195, in open
    response = urlopen(self, req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 352, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 340, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 1215, in https_open
    return self.do_open(conn_factory, req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 1160, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)>`

**Comment by aancw** [comment]
Hi @UltimateHackers , i think you need to add ssl exception or just bypass tlsv1 alert

**Comment by aancw** [comment]
You can see my ssl_checker function https://github.com/aancw/Belati/blob/master/plugins/url_request.py

**Comment by irshad9998** [comment]
Any update bro????

**Comment by UltimateHackers** [comment]
Tomorrow is my last exam. I will fix it and the other issues the next day. 👌🏼

**Comment by UltimateHackers** [comment]
@irshad9998 can you please confirm the fix?

**Comment by irshad9998** [comment]
Not working in mac.

When i run `python3 xsstrike` following error occur.`Traceback (most recent call last):

  File "xsstrike", line 21, in <module>
    from core.injector import inject
  File "/Users/hacker/Downloads/XSStrike-master 2/core/injector.py", line 9, in <module>
    from core.test_param_check import test_param_check
  File "/Users/hacker/Downloads/XSStrike-master 2/core/test_param_check.py", line 4, in <module>
    from fuzzywuzzy import fuzz # Module for fuzzy matching
ImportError: No module named 'fuzzywuzzy'`

**Comment by aancw** [comment]
pip install fuzzywuzzy

**Comment by DeWolfRobin** [comment]
got same even with fuzzywuzzy installed

**Comment by s0md3v** [comment]
@DeWolfRobin You have to do `pip3 install fuzzywuzzy` not `pip install fuzzywuzzy`

**Comment by DeWolfRobin** [comment]
thanks! but now I got this:
Traceback (most recent call last):
  File "xsstrike.py", line 232, in <module>
    singleTarget(target, paramData)
  File "xsstrike.py", line 113, in singleTarget
    params = arjun(url, GET, headers, delay)
  File "/root/XSStrike/core/arjun.py", line 29, in arjun
    for i, _ in enumerate(concurrent.futures.as_completed(futures)):
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 217, in as_completed
    fs = set(fs)
  File "/root/XSStrike/core/arjun.py", line 28, in <genexpr>
    futures = (threadpool.submit(checky, param, paraNames, url, headers, GET, delay) for param in blindParams)
NameError: free variable 'threadpool' referenced before assignment in enclosing scope

**Comment by Amarnath403** [comment]
I am getting a similar error
